'use client';
import {motion,useScroll,useTransform} from 'motion/react';
import {ArrowUpRight,ChevronDown,MapPin,Phone,Play} from 'lucide-react';
import {useRef,useState} from 'react';
const listings=[
{price:'$525,000',place:'Grand Prairie, TX',addr:'3619 Orchard St',meta:'4 beds · 3 baths · 3,274 sqft',img:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=85'},
{price:'$370,000',place:'Dallas, TX',addr:'7153 Teresita Trl',meta:'4 beds · 2.5 baths · 2,232 sqft',img:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85'},
{price:'$314,900',place:'Fort Worth, TX',addr:'2901 Coyote Canyon Trl',meta:'4 beds · 2.5 baths · 2,148 sqft',img:'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1600&q=85'}];
const areas=['Dallas','Fort Worth','Arlington','Grand Prairie','McKinney','Mansfield','Midlothian','Cedar Hill','Plano','Frisco','Euless','Carrollton'];
function Reveal({children,delay=0,className='' }:{children:React.ReactNode;delay?:number;className?:string}){return <motion.div className={className} initial={{opacity:0,y:45,filter:'blur(10px)'}} whileInView={{opacity:1,y:0,filter:'blur(0px)'}} viewport={{once:true,amount:.18}} transition={{duration:.9,delay,ease:[.16,1,.3,1]}}>{children}</motion.div>}
export default function Page(){const ref=useRef<HTMLElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:['start start','end end']});const scale=useTransform(scrollYProgress,[0,.3],[1,1.12]);const [menu,setMenu]=useState(false);return <main ref={ref}>
<motion.div className="progress" style={{scaleX:scrollYProgress}}/>
<nav><a className="logo" href="#top">STAVONA<span>MARIE</span></a><div className="navlinks"><a href="#properties">Properties</a><a href="#approach">Approach</a><a href="#areas">DFW</a><a href="#contact">Contact</a></div><motion.a whileHover={{scale:1.04}} whileTap={{scale:.96}} className="navcta" href="#contact">Let's talk <ArrowUpRight size={15}/></motion.a><button className="hamb" onClick={()=>setMenu(!menu)}>MENU</button></nav>
{menu&&<div className="mobilemenu"><a href="#properties" onClick={()=>setMenu(false)}>Properties</a><a href="#approach" onClick={()=>setMenu(false)}>Approach</a><a href="#areas" onClick={()=>setMenu(false)}>DFW</a><a href="#contact" onClick={()=>setMenu(false)}>Contact</a></div>}
<section id="top" className="hero"><motion.div className="hero-media" style={{scale}}><video autoPlay muted loop playsInline poster="https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=2200&q=90"><source src="https://cdn.coverr.co/videos/coverr-a-modern-house-in-the-hills-1574/1080p.mp4" type="video/mp4"/></video></motion.div><div className="hero-shade"/><div className="hero-copy"><Reveal><p className="eyebrow">DALLAS — FORT WORTH · TEXAS</p><h1>Find the place<br/><i>that feels like you.</i></h1></Reveal><Reveal delay={.18}><div className="hero-bottom"><p>Residential real estate, thoughtfully represented by Stavona Marie.</p><a className="circlebtn" href="#properties"><ChevronDown/></a></div></Reveal></div><div className="hero-credit">REALTOR® · TX #0773087</div></section>
<section className="intro" id="approach"><div className="section-num">01 / APPROACH</div><div><Reveal><h2>Real estate,<br/><i>with intention.</i></h2></Reveal><Reveal delay={.1}><p className="lead">Stavona Marie helps buyers, sellers and relocating professionals navigate the DFW market with clarity—not pressure.</p></Reveal><Reveal delay={.18}><a className="textlink" href="#contact">Meet Stavona <ArrowUpRight size={17}/></a></Reveal></div></section>
<section className="film"><div className="film-bg"><img src="https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=2200&q=90"/><div/></div><div className="film-copy"><span>02 / THE DFW LIFE</span><h2>Move toward<br/><i>what's next.</i></h2><p>From Grand Prairie growth to established Dallas neighborhoods, the right home is about more than an address.</p></div><motion.div className="play"><Play size={16}/></motion.div></section>
<section id="properties" className="properties"><div className="section-head"><div><span>03 / SELECTED HOMES</span><h2>On the market <i>now.</i></h2></div><p>Publicly listed properties associated with Stavona Marie's profile.</p></div><div className="grid">{listings.map((x,i)=><Reveal key={x.addr} delay={i*.1}><motion.article className="property" whileHover="hover"><div className="photo"><motion.img src={x.img} variants={{hover:{scale:1.055}}} transition={{duration:.8}}/><span className="tag">FOR SALE</span><motion.div className="view" variants={{hover:{scale:1,opacity:1}}} initial={{scale:.7,opacity:0}}>VIEW</motion.div></div><div className="pmeta"><span>{x.place}</span><strong>{x.price}</strong></div><h3>{x.addr}</h3><p>{x.meta}</p></article></Reveal>)}</div></section>
<section id="areas" className="areas"><div className="section-num">04 / THE MAP</div><div className="area-copy"><Reveal><h2>Deep roots<br/>across <i>DFW.</i></h2></Reveal><p>Serving buyers and sellers across the Dallas–Fort Worth Metroplex.</p><div className="chips">{areas.map(a=><motion.span key={a} whileHover={{y:-4,scale:1.04}}>{a}</motion.span>)}</div></div><div className="orb"><div className="ring r1"/><div className="ring r2"/><div className="pin"><MapPin size={24}/></div></div></section>
<section className="stats"><Reveal><div><b>5</b><span>YEARS EXPERIENCE</span></div></Reveal><Reveal delay={.08}><div><b>5.0</b><span>PUBLIC RATING</span></div></Reveal><Reveal delay={.16}><div><b>8</b><span>RECENT SALES</span></div></Reveal><Reveal delay={.24}><div><b>$525K</b><span>PUBLIC LISTING HIGH</span></div></Reveal></section>
<section className="story"><div className="portrait"><img src="https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=85"/><small>CONCEPTUAL PORTRAIT — REPLACE WITH APPROVED HEADSHOT</small></div><div className="story-copy"><span>05 / ABOUT STAVONA</span><Reveal><h2>From Flint<br/>to <i>North Texas.</i></h2></Reveal><p>Originally from Flint, Michigan, Stavona moved to Texas in 2013 and now brings a people-first perspective to residential real estate throughout DFW.</p><p>Her publicly listed focus includes healthcare professionals, new builds, relocating clients and single mothers.</p><a className="textlink" href="#contact">Start a conversation <ArrowUpRight size={17}/></a></div></section>
<section id="contact" className="contact"><div className="contact-bg"/><span>06 / LET'S TALK</span><Reveal><h2>Ready for a<br/><i>different move?</i></h2></Reveal><motion.a whileHover={{scale:1.03}} whileTap={{scale:.98}} className="bigcta" href="tel:+18103479374">(810) 347-9374 <ArrowUpRight/></motion.a><p>Bobby Bryant Properties · REALTOR® TX #0773087</p></section>
<footer><span>STAVONA MARIE</span><span>DFW · TEXAS</span><span>© 2026</span></footer>
</main>}
